#!/usr/bin/env bash
# Manatee Device Client — First-Time Setup Script
# Run with: sudo bash setup.sh
#
# Reads config from boot partition (if present) or prompts interactively.
set -euo pipefail

# ── Step 1: Check root ──────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
    echo "ERROR: This script must be run as root."
    echo "Usage: sudo bash setup.sh"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
echo ""
echo "=== Manatee Device Client — Setup ==="
echo ""

# ── Step 2: Find boot partition config ──────────────────────────────
BOOT_CONFIG=""
if [[ -f /boot/firmware/manatee.conf ]]; then
    BOOT_CONFIG="/boot/firmware/manatee.conf"
elif [[ -f /boot/manatee.conf ]]; then
    BOOT_CONFIG="/boot/manatee.conf"
fi

# ── Step 3: Read or prompt for config values ────────────────────────
if [[ -n "$BOOT_CONFIG" ]]; then
    echo "Found boot config at: $BOOT_CONFIG"
    source "$BOOT_CONFIG"
    echo "  API Key: ${MANATEE_API_KEY:0:9}..."
    echo "  Server:  $MANATEE_SERVER_URL"
    echo ""
else
    echo "No boot config found. Please enter values manually."
    echo ""
    read -rp "API Key (mntk_...): " MANATEE_API_KEY
    read -rp "Server URL (e.g., https://manatee.example.com): " MANATEE_SERVER_URL
    echo ""
fi

# Validate
if [[ ! "$MANATEE_API_KEY" =~ ^mntk_ ]]; then
    echo "ERROR: API key must start with 'mntk_'"
    exit 1
fi
if [[ -z "$MANATEE_SERVER_URL" ]]; then
    echo "ERROR: Server URL is required"
    exit 1
fi

# ── Step 4: Install system dependencies ─────────────────────────────
echo "Installing system dependencies..."
apt-get update -qq
apt-get install -y -qq python3 python3-venv libsndfile1 portaudio19-dev > /dev/null
echo "  Done."

# ── Step 5: Ensure NTP is enabled (prevent clock drift) ────────────
echo "Enabling NTP time sync..."
timedatectl set-ntp true 2>/dev/null || true
echo "  Done."

# ── Step 6: Create system user ─────────────────────────────────────
if ! id -u manatee &>/dev/null; then
    echo "Creating 'manatee' system user..."
    useradd --system --no-create-home --shell /usr/sbin/nologin manatee
    echo "  Done."
else
    echo "System user 'manatee' already exists."
fi

# ── Step 7: Create directories ──────────────────────────────────────
echo "Creating directories..."
mkdir -p /opt/manatee
mkdir -p /etc/manatee
mkdir -p /var/lib/manatee/outbox
mkdir -p /var/lib/manatee/failed
mkdir -p /var/lib/manatee/incoming
mkdir -p /var/lib/manatee/incoming/processing
mkdir -p /var/lib/manatee/archive
mkdir -p /var/lib/manatee/.numba_cache
echo "  Done."

# ── Step 8: Copy client code and create venv ────────────────────────
echo "Installing client code..."
cp -r "$SCRIPT_DIR/manatee_client" /opt/manatee/
cp "$SCRIPT_DIR/requirements.txt" /opt/manatee/

echo "Creating Python virtual environment..."
python3 -m venv /opt/manatee/venv
/opt/manatee/venv/bin/pip install --upgrade pip -q
/opt/manatee/venv/bin/pip install -r /opt/manatee/requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu -q
echo "  Done."

# ── Step 8b: Copy ML model ─────────────────────────────────────────────
if [[ -f "$SCRIPT_DIR/manatee_model.pt" ]]; then
    echo "Copying ML model..."
    cp "$SCRIPT_DIR/manatee_model.pt" /opt/manatee/
    echo "  Done."
else
    echo "  WARNING: manatee_model.pt not found in $SCRIPT_DIR"
    echo "  Place the model file at /opt/manatee/manatee_model.pt before starting the service."
fi

# ── Step 9: Write permanent config ─────────────────────────────────
echo "Writing config to /etc/manatee/config.env..."
cat > /etc/manatee/config.env << EOF
# Manatee Device Configuration
# Generated by setup.sh on $(date -Iseconds)
MANATEE_API_KEY=$MANATEE_API_KEY
MANATEE_SERVER_URL=$MANATEE_SERVER_URL
MANATEE_HEARTBEAT_INTERVAL=300
MANATEE_OUTBOX_DIR=/var/lib/manatee/outbox
MANATEE_FAILED_DIR=/var/lib/manatee/failed
MANATEE_LOG_LEVEL=INFO
MANATEE_MODEL_PATH=/opt/manatee/manatee_model.pt
MANATEE_INCOMING_DIR=/var/lib/manatee/incoming
MANATEE_ARCHIVE_DIR=/var/lib/manatee/archive
MANATEE_DETECTION_LOG=/var/lib/manatee/detections.jsonl
MANATEE_INFERENCE_ENABLED=true
MANATEE_AUDIO_SOURCE=hydrophone
# MANATEE_AUDIO_DEVICE=
# MANATEE_SEGMENT_DURATION=30
EOF
chmod 600 /etc/manatee/config.env
echo "  Done."

# ── Step 10: Remove boot config (security) ──────────────────────────
if [[ -n "$BOOT_CONFIG" ]]; then
    echo "Removing API key from boot partition..."
    rm -f "$BOOT_CONFIG"
    echo "  Done (key is now only in /etc/manatee/config.env with chmod 600)."
fi

# ── Step 11: Set ownership ──────────────────────────────────────────
echo "Setting file ownership..."
chown -R manatee:manatee /opt/manatee
chown -R manatee:manatee /var/lib/manatee
chown -R manatee:manatee /etc/manatee
echo "  Done."

# ── Step 12: Install systemd service ────────────────────────────────
echo "Installing systemd service..."
cp "$SCRIPT_DIR/manatee-device.service" /etc/systemd/system/
systemctl daemon-reload
systemctl enable manatee-device.service
echo "  Done."

# ── Step 13: Test connectivity ──────────────────────────────────────
echo ""
echo "Testing connection to $MANATEE_SERVER_URL..."
CONN_OUTPUT=$(sudo -u manatee /opt/manatee/venv/bin/python3 -c "
import requests, sys
try:
    r = requests.get(
        '${MANATEE_SERVER_URL}/api/devices/me',
        headers={'X-Device-Key': '${MANATEE_API_KEY}'},
        timeout=10,
    )
    if r.status_code == 200:
        data = r.json()
        # Cache device ID
        with open('/etc/manatee/config.env', 'a') as f:
            f.write('MANATEE_DEVICE_ID=' + str(data['id']) + '\n')
        print('OK:' + data['device_name'] + ':' + str(data['id']))
    else:
        print('FAIL:' + str(r.status_code) + ':' + r.text[:200])
except Exception as e:
    print('FAIL:error:' + str(e))
" 2>&1) || true

if [[ "$CONN_OUTPUT" == OK:* ]]; then
    DEVICE_NAME=$(echo "$CONN_OUTPUT" | cut -d: -f2)
    DEVICE_ID=$(echo "$CONN_OUTPUT" | cut -d: -f3)
    echo "  Connected! Device: $DEVICE_NAME (ID: $DEVICE_ID)"
    echo ""

    # ── Step 14: Start service ──────────────────────────────────────
    echo "Starting manatee-device service..."
    systemctl start manatee-device.service
    echo "  Service started."
else
    echo "  WARNING: Could not connect to server."
    echo "  Output: $CONN_OUTPUT"
    echo ""
    echo "  The service has been installed but NOT started."
    echo "  It will auto-discover the device ID on first successful connection."
    echo "  Start manually with: sudo systemctl start manatee-device"
fi

# ── Step 15: Print summary ──────────────────────────────────────────
echo ""
echo "=========================================="
echo "  Manatee Device Setup Complete"
echo "=========================================="
echo ""
echo "  Config:   /etc/manatee/config.env"
echo "  Client:   /opt/manatee/"
echo "  Model:    /opt/manatee/manatee_model.pt"
echo "  Incoming: /var/lib/manatee/incoming/"
echo "  Outbox:   /var/lib/manatee/outbox/"
echo "  Archive:  /var/lib/manatee/archive/"
echo "  Failed:   /var/lib/manatee/failed/"
echo "  Log:      /var/lib/manatee/detections.jsonl"
echo ""
echo "  View logs:      sudo journalctl -u manatee-device -f"
echo "  Check status:   sudo systemctl status manatee-device"
echo "  Restart:        sudo systemctl restart manatee-device"
echo ""
echo "  To process audio, place files in /var/lib/manatee/incoming/"
echo "  The device will run ML inference and upload results automatically."
echo ""
